from datetime import datetime, timedelta
from collections import defaultdict

# Known malicious IPs (would come from a threat feed in production)
KNOWN_MALICIOUS_IPS = {"45.33.32.156", "185.220.101.5", "198.51.100.7"}

# Thresholds
BRUTE_FORCE_THRESHOLD = 3       # failed logins per IP in window
BRUTE_FORCE_WINDOW_SEC = 60
PORT_SCAN_THRESHOLD = 5         # distinct ports per IP in window
TRAFFIC_SPIKE_THRESHOLD = 50    # total logs to trigger spike alert

# Persistent state across requests
_failed_login_times: dict[str, list[datetime]] = defaultdict(list)
_port_access_times: dict[str, dict[int, list[datetime]]] = defaultdict(lambda: defaultdict(list))
_alert_store: list[dict] = []


def _now() -> datetime:
    return datetime.utcnow()


def _clean_window(times: list[datetime], window_sec: int) -> list[datetime]:
    cutoff = _now() - timedelta(seconds=window_sec)
    return [t for t in times if t > cutoff]


def _add_alert(severity: str, message: str, src_ip: str = ""):
    alert = {
        "timestamp": _now().isoformat(timespec="seconds") + "Z",
        "severity": severity,   # "LOW", "MEDIUM", "HIGH", "CRITICAL"
        "message": message,
        "src_ip": src_ip,
    }
    _alert_store.append(alert)
    return alert


def get_all_alerts() -> list[dict]:
    return list(reversed(_alert_store))


def detect_suspicious(logs: list[dict]) -> list[dict]:
    """
    Analyse a batch of new logs against persistent state.
    Returns any NEW alerts generated by this batch.
    """
    new_alerts = []
    total_logs = len(logs)

    ip_failed_counts: dict[str, int] = defaultdict(int)

    for log in logs:
        src_ip = log.get("src_ip", "")
        port = log.get("port", 0)
        status = log.get("status", "")
        now = _now()

        # ── 1. Known malicious IP ──────────────────────────────────────────
        if src_ip in KNOWN_MALICIOUS_IPS:
            alert = _add_alert("CRITICAL", f"Known malicious IP contacted the network", src_ip)
            new_alerts.append(alert)

        # ── 2. Brute-force detection (persistent across requests) ──────────
        if status == "FAILED_LOGIN":
            _failed_login_times[src_ip].append(now)
            _failed_login_times[src_ip] = _clean_window(
                _failed_login_times[src_ip], BRUTE_FORCE_WINDOW_SEC
            )
            count = len(_failed_login_times[src_ip])
            ip_failed_counts[src_ip] = count

            if count == BRUTE_FORCE_THRESHOLD:  # alert once at threshold
                alert = _add_alert(
                    "HIGH",
                    f"Brute-force attack detected: {count} failed logins in {BRUTE_FORCE_WINDOW_SEC}s",
                    src_ip,
                )
                new_alerts.append(alert)

        # ── 3. Port scan detection ─────────────────────────────────────────
        _port_access_times[src_ip][port].append(now)
        # Clean each port's window
        for p in list(_port_access_times[src_ip]):
            _port_access_times[src_ip][p] = _clean_window(
                _port_access_times[src_ip][p], BRUTE_FORCE_WINDOW_SEC
            )
        active_ports = [p for p, ts in _port_access_times[src_ip].items() if ts]
        if len(active_ports) >= PORT_SCAN_THRESHOLD:
            alert = _add_alert(
                "HIGH",
                f"Port scan detected: {len(active_ports)} distinct ports probed",
                src_ip,
            )
            new_alerts.append(alert)
            # Reset to avoid duplicate storm
            _port_access_times[src_ip] = defaultdict(list)

    # ── 4. Traffic spike ───────────────────────────────────────────────────
    if total_logs >= TRAFFIC_SPIKE_THRESHOLD:
        alert = _add_alert(
            "MEDIUM",
            f"Unusual traffic spike: {total_logs} events in a single batch",
        )
        new_alerts.append(alert)

    return new_alerts